// Code generated by mockery v1.0.0
package mocks

import api "github.com/veritone/webstream-adapter/api"
import context "context"
import mock "github.com/stretchr/testify/mock"

// CoreAPIClient is an autogenerated mock type for the CoreAPIClient type
type CoreAPIClient struct {
	mock.Mock
}

// FetchSource provides a mock function with given fields: ctx, sourceID
func (_m *CoreAPIClient) FetchSource(ctx context.Context, sourceID string) (*api.Source, error) {
	ret := _m.Called(ctx, sourceID)

	var r0 *api.Source
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.Source); ok {
		r0 = rf(ctx, sourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Source)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
